Repository GlobalX/pockybot, pull requests merged in 2019-07, with the labels that each got.

#132 Penalise penalty keywords
  package-lock.json
  package.json
  src/lib/parsers/htmlHelper.ts
  src/lib/parsers/tableHelper.ts
  src/lib/response-triggers/index.ts
  src/lib/response-triggers/pm-index.ts
  src/lib/services/category-results-service.ts
  src/lib/services/format-results-service.ts
  src/lib/services/peg-service.ts
  src/lib/services/pm-results-service.ts
  src/lib/services/results-service.ts
  src/lib/services/winners-service.ts
  src/lib/utilities.ts
  src/models/peg-recipient.ts
  src/models/peg.ts
  src/models/receiver.ts
  src/models/result.ts
  src/spec/category-results-service-spec.ts
  src/spec/format-results-service-spec.ts
  src/spec/mocks/mock-category-results-service.ts
  src/spec/mocks/mock-results-service.ts
  src/spec/mocks/mock-winners-service.ts
  src/spec/pm-results-service-spec.ts
  src/spec/pocky-db-spec.ts
  src/spec/results-service-spec.ts
  src/spec/roleconfig-spec.ts
  src/spec/services/mock-data-service.ts
  src/spec/services/test-equality-services.ts
  src/spec/status-spec.ts
  src/spec/unpeg-spec.ts
  src/spec/winners-service-spec.ts
Labels: enhancement

#148 Add dependabot config
  .dependabot/config.yml
Labels: maintenance

#150 Add badges to readme
  README.md
Labels: maintenance

#154 improve GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: maintenance

#156 fix vulnerabilities
  package-lock.json
Labels: dependencies, maintenance, security

#155 chore: add commit hook for message format
  commitlint.config.js
  package-lock.json
  package.json
Labels: maintenance

#170 Bugfix/151 fix winners order
  src/lib/services/results-service.ts
Labels: bug

#160 Feature/152 remove winners from finish message
  src/lib/response-triggers/finish.ts
  src/lib/services/pm-results-service.ts
Labels: bug, enhancement

#171 fix(ci): fix release script
  .travis.yml
Labels: bug
