Repository GlobalX/pockybot, pull requests merged in 2019-01, with the labels that each got.

#19 improve response to status message when user has not given any pegs
  src/lib/response-triggers/status.ts
Labels: enhancement

#24 Update help message for admins
  src/constants.ts
  src/lib/response-triggers/help.ts
  src/spec/help-spec.ts
  src/spec/keywords-spec.ts
  src/spec/peg-spec.ts
  src/spec/ping-spec.ts
  src/spec/reset-spec.ts
  src/spec/results-spec.ts
  src/spec/status-spec.ts
  src/spec/unpeg-spec.ts
  src/spec/welcome-spec.ts
  src/spec/winners-spec.ts
Labels: enhancement

#28 Feature/html results file
  kubernetes/deployment.yml
  package-lock.json
  package.json
  pr-config.yml
  src/constants.ts
  src/lib/registerhooks.ts
  src/lib/response-triggers/finish.ts
  src/lib/response-triggers/results.ts
  src/server.ts
  src/spec/results-spec.ts
  tsconfig.build.json
  tsconfig.json
Labels: enhancement

#34 Stop suppressing mentions of other people in comments
  src/lib/parsers/xmlMessageParser.ts
Labels: bug

#38 Update readme and contribution guidelines
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  src/constants.ts
Labels: maintenance
